import mongoose from "mongoose";
import dotenv from "dotenv";
import ProductModel from "./models/productModel.js";

dotenv.config();

const categoriesProducts = [
  // ================= ELECTRONICS (5 Products) =================
  {
    productId: `TM_ELEC_${Date.now()}_1`,
    header: "Electronics",
    productCategory: "Electronics",
    otherCategory: "Audio",
    productName: "Sony WH-1000XM5 Wireless Headphones",
    productType: "Headphones",
    productBrand: "Sony",
    availableStockQty: 45,
    mrp: 29990,
    offerPrice: 24990,
    packetweight: 250,
    unitOfMeasure: "g",
    description: "Industry-leading noise canceling headphones with Auto NC Optimizer, crystal clear hands-free calling, and 30-hour battery life.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-10",
    expiryDate: "2029-01-10",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: true,
    tekiskyPrice: "24990",
    color: "Black"
  },
  {
    productId: `TM_ELEC_${Date.now()}_2`,
    header: "Electronics",
    productCategory: "Electronics",
    otherCategory: "Speakers",
    productName: "JBL Flip 6 Portable Waterproof Speaker",
    productType: "Bluetooth Speaker",
    productBrand: "JBL",
    availableStockQty: 60,
    mrp: 13999,
    offerPrice: 9999,
    packetweight: 550,
    unitOfMeasure: "g",
    description: "Louder, more powerful sound with IP67 waterproof and dustproof design, 12 hours of playtime.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-05",
    expiryDate: "2029-02-05",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "9999",
    color: "Red"
  },
  {
    productId: `TM_ELEC_${Date.now()}_3`,
    header: "Electronics",
    productCategory: "Electronics",
    otherCategory: "Displays",
    productName: "Samsung 27-inch Curved Gaming Monitor",
    productType: "Monitor",
    productBrand: "Samsung",
    availableStockQty: 25,
    mrp: 22000,
    offerPrice: 16499,
    packetweight: 4500,
    unitOfMeasure: "g",
    description: "144Hz refresh rate curved gaming monitor with AMD FreeSync for smooth visual performance.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-20",
    expiryDate: "2030-01-20",
    sellerInformation: "Tekisky Tech Hub",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "16499",
    color: "Dark Blue"
  },
  {
    productId: `TM_ELEC_${Date.now()}_4`,
    header: "Electronics",
    productCategory: "Electronics",
    otherCategory: "Computers",
    productName: "Logitech MX Master 3S Wireless Mouse",
    productType: "Computer Accessory",
    productBrand: "Logitech",
    availableStockQty: 80,
    mrp: 10995,
    offerPrice: 8995,
    packetweight: 141,
    unitOfMeasure: "g",
    description: "Quiet clicks ergonomics wireless mouse with 8K DPI any-surface tracking and MagSpeed scrolling.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-03-01",
    expiryDate: "2029-03-01",
    sellerInformation: "Tekisky Tech Hub",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "8995",
    color: "Graphite"
  },
  {
    productId: `TM_ELEC_${Date.now()}_5`,
    header: "Electronics",
    productCategory: "Electronics",
    otherCategory: "Cameras",
    productName: "Canon EOS R10 Mirrorless Camera",
    productType: "Camera",
    productBrand: "Canon",
    availableStockQty: 15,
    mrp: 92995,
    offerPrice: 80990,
    packetweight: 429,
    unitOfMeasure: "g",
    description: "24.2 MP APS-C sensor camera with Dual Pixel CMOS AF II and 4K 60p video capabilities.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-15",
    expiryDate: "2031-02-15",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: true,
    tekiskyPrice: "80990",
    color: "Black"
  },

  // ================= MOBILES & WEARABLES (5 Products) =================
  {
    productId: `TM_MOB_${Date.now()}_1`,
    header: "Mobiles",
    productCategory: "Mobiles",
    otherCategory: "Smartphones",
    productName: "Apple iPhone 15 (128GB) - Black",
    productType: "Smartphone",
    productBrand: "Apple",
    availableStockQty: 30,
    mrp: 79900,
    offerPrice: 71990,
    packetweight: 171,
    unitOfMeasure: "g",
    description: "Dynamic Island, 48MP main camera, USB-C connectivity, and durable color-infused glass design.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-05",
    expiryDate: "2030-01-05",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: true,
    tekiskyPrice: "71990",
    color: "Black"
  },
  {
    productId: `TM_MOB_${Date.now()}_2`,
    header: "Mobiles",
    productCategory: "Mobiles",
    otherCategory: "Smartphones",
    productName: "OnePlus 12R 5G (Cool Blue, 256GB)",
    productType: "Smartphone",
    productBrand: "OnePlus",
    availableStockQty: 40,
    mrp: 45999,
    offerPrice: 39999,
    packetweight: 207,
    unitOfMeasure: "g",
    description: "Snapdragon 8 Gen 2, 120 Hz AMOLED display with 100W SUPERVOOC charging.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-12",
    expiryDate: "2030-02-12",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "39999",
    color: "Cool Blue"
  },
  {
    productId: `TM_MOB_${Date.now()}_3`,
    header: "Mobiles",
    productCategory: "Mobiles",
    otherCategory: "Smartwatches",
    productName: "Apple Watch Series 9 GPS 45mm",
    productType: "Smartwatch",
    productBrand: "Apple",
    availableStockQty: 20,
    mrp: 44900,
    offerPrice: 41900,
    packetweight: 39,
    unitOfMeasure: "g",
    description: "S9 SiP chip, double tap gesture control, brighter display, and advanced health metrics tracking.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-25",
    expiryDate: "2029-01-25",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "41900",
    color: "Midnight"
  },
  {
    productId: `TM_MOB_${Date.now()}_4`,
    header: "Mobiles",
    productCategory: "Mobiles",
    otherCategory: "Earbuds",
    productName: "Nothing Ear (2) TWS Wireless Earbuds",
    productType: "Earbuds",
    productBrand: "Nothing",
    availableStockQty: 55,
    mrp: 9999,
    offerPrice: 6999,
    packetweight: 52,
    unitOfMeasure: "g",
    description: "Hi-Res Audio certified TWS with 36 dB active noise cancellation and personalized sound profile.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-03-05",
    expiryDate: "2029-03-05",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "6999",
    color: "White"
  },
  {
    productId: `TM_MOB_${Date.now()}_5`,
    header: "Mobiles",
    productCategory: "Mobiles",
    otherCategory: "Accessories",
    productName: "Anker 10000mAh Magnetic Wireless Power Bank",
    productType: "Power Bank",
    productBrand: "Anker",
    availableStockQty: 90,
    mrp: 4999,
    offerPrice: 3499,
    packetweight: 220,
    unitOfMeasure: "g",
    description: "MagSafe compatible portable charger with foldable stand for fast wireless charging.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1609592424009-598971f11c7c?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-18",
    expiryDate: "2028-02-18",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "3499",
    color: "Black"
  },

  // ================= CLOTHING & FASHION (5 Products) =================
  {
    productId: `TM_CLOTH_${Date.now()}_1`,
    header: "Clothing",
    productCategory: "Clothing",
    otherCategory: "Men's Wear",
    productName: "Men's Slim Fit Denim Jacket",
    productType: "Jacket",
    productBrand: "Levi's",
    availableStockQty: 50,
    mrp: 4999,
    offerPrice: 2999,
    packetweight: 650,
    unitOfMeasure: "g",
    description: "Classic rugged blue denim trucker jacket crafted with 100% durable cotton.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-18",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Fashion Hub",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "2999",
    size: "L",
    color: "Blue Denim",
    material: "Denim"
  },
  {
    productId: `TM_CLOTH_${Date.now()}_2`,
    header: "Clothing",
    productCategory: "Clothing",
    otherCategory: "Women's Wear",
    productName: "Women's Floral Print Summer Maxidress",
    productType: "Dress",
    productBrand: "Zara",
    availableStockQty: 35,
    mrp: 3590,
    offerPrice: 2199,
    packetweight: 350,
    unitOfMeasure: "g",
    description: "Elegant breathable chiffon maxi dress with vibrant summer floral patterns.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-14",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Fashion Hub",
    approved: true,
    dealOfDay: true,
    tekiskyPrice: "2199",
    size: "M",
    color: "Multicolor",
    material: "Chiffon"
  },
  {
    productId: `TM_CLOTH_${Date.now()}_3`,
    header: "Clothing",
    productCategory: "Clothing",
    otherCategory: "Casual Wear",
    productName: "Unisex Oversized Heavyweight Hoodie",
    productType: "Hoodie",
    productBrand: "H&M",
    availableStockQty: 75,
    mrp: 2499,
    offerPrice: 1599,
    packetweight: 500,
    unitOfMeasure: "g",
    description: "Cozy fleece-lined streetwear hoodie designed for extreme comfort and style.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-30",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Fashion Hub",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "1599",
    size: "XL",
    color: "Beige",
    material: "Cotton Blend"
  },
  {
    productId: `TM_CLOTH_${Date.now()}_4`,
    header: "Clothing",
    productCategory: "Clothing",
    otherCategory: "Formal Wear",
    productName: "Men's Premium Cotton Formal Shirt",
    productType: "Shirt",
    productBrand: "Raymond",
    availableStockQty: 40,
    mrp: 1999,
    offerPrice: 1299,
    packetweight: 250,
    unitOfMeasure: "g",
    description: "Crisp wrinkle-resistant formal white shirt made for business meetings and occasions.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-20",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Fashion Hub",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "1299",
    size: "L",
    color: "White",
    material: "100% Cotton"
  },
  {
    productId: `TM_CLOTH_${Date.now()}_5`,
    header: "Clothing",
    productCategory: "Clothing",
    otherCategory: "Activewear",
    productName: "Nike Dri-FIT Running Trousers",
    productType: "Trackpants",
    productBrand: "Nike",
    availableStockQty: 60,
    mrp: 3295,
    offerPrice: 2495,
    packetweight: 300,
    unitOfMeasure: "g",
    description: "Moisture-wicking athletic joggers engineered for optimal airflow during workouts.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-03-02",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Fashion Hub",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "2495",
    size: "M",
    color: "Black",
    material: "Polyester"
  },

  // ================= FOOTWEAR (5 Products) =================
  {
    productId: `TM_FOOT_${Date.now()}_1`,
    header: "Footwear",
    productCategory: "Footwear",
    otherCategory: "Sports Shoes",
    productName: "Nike Air Max 270 Sneakers",
    productType: "Sneakers",
    productBrand: "Nike",
    availableStockQty: 30,
    mrp: 14995,
    offerPrice: 11995,
    packetweight: 800,
    unitOfMeasure: "g",
    description: "Big Air unit delivers unmatched all-day comfort with sleek modern aesthetic.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-12",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: true,
    tekiskyPrice: "11995",
    size: "UK 9",
    color: "Red & White"
  },
  {
    productId: `TM_FOOT_${Date.now()}_2`,
    header: "Footwear",
    productCategory: "Footwear",
    otherCategory: "Casual Shoes",
    productName: "Adidas Ultraboost Light Running Shoes",
    productType: "Running Shoes",
    productBrand: "Adidas",
    availableStockQty: 40,
    mrp: 18999,
    offerPrice: 14999,
    packetweight: 750,
    unitOfMeasure: "g",
    description: "Lightest Ultraboost ever with Light BOOST material for maximum energy return.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-08",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "14999",
    size: "UK 10",
    color: "Core Black"
  },
  {
    productId: `TM_FOOT_${Date.now()}_3`,
    header: "Footwear",
    productCategory: "Footwear",
    otherCategory: "Sneakers",
    productName: "Puma RS-X Triple Unisex Sneakers",
    productType: "Sneakers",
    productBrand: "Puma",
    availableStockQty: 50,
    mrp: 9999,
    offerPrice: 5999,
    packetweight: 850,
    unitOfMeasure: "g",
    description: "Retro-futuristic silhouette with bulky design and comfortable cushioning tech.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-22",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "5999",
    size: "UK 8",
    color: "White / Gray"
  },
  {
    productId: `TM_FOOT_${Date.now()}_4`,
    header: "Footwear",
    productCategory: "Footwear",
    otherCategory: "Formal Shoes",
    productName: "Clarks Genuine Leather Oxford Shoes",
    productType: "Formal Shoes",
    productBrand: "Clarks",
    availableStockQty: 25,
    mrp: 7999,
    offerPrice: 5499,
    packetweight: 900,
    unitOfMeasure: "g",
    description: "Handcrafted full-grain leather Oxfords for business suits and special events.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-28",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Fashion Hub",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "5499",
    size: "UK 9",
    color: "Tan Brown",
    material: "Leather"
  },
  {
    productId: `TM_FOOT_${Date.now()}_5`,
    header: "Footwear",
    productCategory: "Footwear",
    otherCategory: "Sandals",
    productName: "Crocs Classic Clog Slip-On",
    productType: "Clogs",
    productBrand: "Crocs",
    availableStockQty: 100,
    mrp: 3495,
    offerPrice: 2495,
    packetweight: 350,
    unitOfMeasure: "g",
    description: "Lightweight, water-friendly, and buoyant ventilation ports for breathability.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-03-10",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "2495",
    size: "UK 9",
    color: "Navy"
  },

  // ================= HOME & KITCHEN (5 Products) =================
  {
    productId: `TM_HOME_${Date.now()}_1`,
    header: "Home & Kitchen",
    productCategory: "Home & Kitchen",
    otherCategory: "Appliances",
    productName: "Philips Digital Air Fryer HD9252",
    productType: "Air Fryer",
    productBrand: "Philips",
    availableStockQty: 30,
    mrp: 11995,
    offerPrice: 8499,
    packetweight: 4500,
    unitOfMeasure: "g",
    description: "Rapid Air Technology cooks delicious food with up to 90% less fat.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-15",
    expiryDate: "2030-01-15",
    sellerInformation: "Tekisky Home Care",
    approved: true,
    dealOfDay: true,
    tekiskyPrice: "8499",
    color: "Black"
  },
  {
    productId: `TM_HOME_${Date.now()}_2`,
    header: "Home & Kitchen",
    productCategory: "Home & Kitchen",
    otherCategory: "Coffee Makers",
    productName: "Nespresso Essenza Mini Espresso Machine",
    productType: "Coffee Maker",
    productBrand: "Nespresso",
    availableStockQty: 20,
    mrp: 15999,
    offerPrice: 12499,
    packetweight: 2300,
    unitOfMeasure: "g",
    description: "Ultra-compact espresso maker with 19-bar high-pressure pump for barista quality coffee.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1517668808822-9eaa02afd2a2?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-01",
    expiryDate: "2030-02-01",
    sellerInformation: "Tekisky Home Care",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "12499",
    color: "Red"
  },
  {
    productId: `TM_HOME_${Date.now()}_3`,
    header: "Home & Kitchen",
    productCategory: "Home & Kitchen",
    otherCategory: "Vacuums",
    productName: "Dyson V12 Detect Slim Vacuum Cleaner",
    productType: "Vacuum Cleaner",
    productBrand: "Dyson",
    availableStockQty: 10,
    mrp: 55900,
    offerPrice: 47900,
    packetweight: 2200,
    unitOfMeasure: "g",
    description: "Laser reveals invisible dust on hard floors with intelligent suction adjustment.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-01-22",
    expiryDate: "2032-01-22",
    sellerInformation: "Tekisky Official Store",
    approved: true,
    dealOfDay: true,
    tekiskyPrice: "47900",
    color: "Yellow / Nickel"
  },
  {
    productId: `TM_HOME_${Date.now()}_4`,
    header: "Home & Kitchen",
    productCategory: "Home & Kitchen",
    otherCategory: "Cookware",
    productName: "Prestige 3-Piece Non-Stick Cookware Set",
    productType: "Cookware",
    productBrand: "Prestige",
    availableStockQty: 65,
    mrp: 3499,
    offerPrice: 2199,
    packetweight: 3100,
    unitOfMeasure: "g",
    description: "Includes Dosa Tawa, Fry Pan, and Kadam with durable 5-layer non-stick coating.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-02-19",
    expiryDate: "N/A",
    sellerInformation: "Tekisky Home Care",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "2199",
    color: "Black"
  },
  {
    productId: `TM_HOME_${Date.now()}_5`,
    header: "Home & Kitchen",
    productCategory: "Home & Kitchen",
    otherCategory: "Purifiers",
    productName: "Kent Grand Plus RO + UV Water Purifier",
    productType: "Water Purifier",
    productBrand: "Kent",
    availableStockQty: 25,
    mrp: 20000,
    offerPrice: 15499,
    packetweight: 8500,
    unitOfMeasure: "g",
    description: "Multiple purification process of RO+UV+UF+TDS Control retains essential minerals.",
    createdBy: "0000000000",
    imageURL: ["https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop"],
    manufactureDate: "2024-03-01",
    expiryDate: "2030-03-01",
    sellerInformation: "Tekisky Home Care",
    approved: true,
    dealOfDay: false,
    tekiskyPrice: "15499",
    color: "White"
  }
];

const seedProducts = async () => {
  try {
    const dbUrl = process.env.DBURL;
    const dbName = process.env.DBNAME || "TekiskyMart-old";
    console.log("Connecting to Database...");
    await mongoose.connect(dbUrl, { dbName: dbName });
    console.log("Connected successfully!");

    console.log("Inserting 25 real products across 5 categories (5 products per category)...");
    const result = await ProductModel.insertMany(categoriesProducts);

    console.log(`Successfully added ${result.length} original products into MongoDB database!`);
    process.exit(0);
  } catch (error) {
    console.error("Error inserting products:", error);
    process.exit(1);
  }
};

seedProducts();
